### ISSUE TITLE
Consider migrating to github pages deployment

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-common#272]
Travis has a built-in [provider for github pages](https://docs.travis-ci.com/user/deployment/pages/) which this [script](https://github.com/googleapis/google-cloud-common/blob/master/deploy-docs.sh) is currently doing manually. `deploy-docs.sh` should be scrapped in favor of something like the following inside `.travis.yml`:

```
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
```

In this case, `GITHUB_TOKEN` should be a personal access token, rather than an OAuth token, that can be set in the Travis settings.

The install/linking/testing steps should be moved to `.travis.yml` too.
